In [3]:
import pandas as pd
import numpy as np
a=[[2,3,np.nan,4],[3,9,np.nan,2]]
print(a)
arr=np.nan_to_num(a,nan=0)
print(arr)
df=pd.DataFrame(a)
print(df)

df.fillna(0, inplace=True)
print(df)
arrt=np.array([[6,-8,73,-110],[np.nan,-8,0,94]])

print(a)
arr_trans=arrt.T
print(arr_trans)

[[2, 3, nan, 4], [3, 9, nan, 2]]
[[2. 3. 0. 4.]
 [3. 9. 0. 2.]]
   0  1   2  3
0  2  3 NaN  4
1  3  9 NaN  2
   0  1    2  3
0  2  3  0.0  4
1  3  9  0.0  2
[[   6.   nan]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]
[[   6.   nan]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [5]:
#2) Move axes of a 3D array to new positions
arr=np.arange(24).reshape(2,3,4)
print(arr,arr.shape)
d=np.moveaxis(arr,0,2)
print(d,d.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]] (3, 4, 2)


In [16]:

import numpy as np
#3) Replace NaN values with average of columns
a=np.array([[2,3,np.nan,4],[3,9,np.nan,2]])
print(a)
d=np.nanmean(arr,axis=0)
#indices
inds=np.where(np.isnan(a))
a[inds]=np.take(d,inds[1])

print(a)

[[ 2.  3. nan  4.]
 [ 3.  9. nan  2.]]
[[2. 3. 8. 4.]
 [3. 9. 8. 2.]]


In [17]:
arr = np.array([10, -5, 20, -8, 15])
arr=np.where(arr<0,0,arr)
print(arr)

[10  0 20  0 15]
