In [10]:
import numpy as np
a=np.array([1,4,3,2,6,7])
print(a)
s=a.reshape(3,2)
print(s)
print("shape:",s.shape)
print("dimensin",s.ndim)
print(s.dtype)
print("item size",s.itemsize)
f=np.full((3,3),9)
print(f)
# 3. 10 evenly spaced values between 25 and 125
d=np.linspace(25,125,10)
print("linspace arr:",d)
a=[2,4,6,7]
s=np.array(a)
print(s)
#reverse
r=s[:: -1]
print(r)
arr=np.array([
    [
        [3,4,1],[5,8,6],[2,11,4],[2,3,9]],[[2,4,8],[12,3,5],[6,1,7],[2,3,8]],[[12,34,5],[6,9,8],[23,4,7],[4,3,13]],[[34,2,1],[1,3,8],[56,9,0],[5,8,3]]
                                                                                                         
                                                    
])
print(arr)
print(arr[1,0,2])
# 7. Create 4x4 and extract odd rows and even columns
f = np.arange(1, 17).reshape(4, 4)
print("\n4x4 Array:\n", f)

print("\nOdd Rows & Even Columns:")
print(f[1::2, ::2])

# 8. First two rows and first two columns of second set
print("\nSlice from second set:")
print(arr[1, :2, :2])

# 9. Replace odd numbers with -1 using for loop
g = np.array([[23, 56, 78, 93],
              [71, 82, 13, 24]])

for i in range(g.shape[0]):
    for j in range(g.shape[1]):
        if g[i, j] % 2 != 0:
            g[i, j] = -1

print("\nOdd replaced with -1:\n", g)

# 10. Indices of non-zero elements
h = np.array([1, 0, 2, 0, 3, 0, 4])

print("\nNon-zero indices:")
print(np.nonzero(h))

# 11. Arithmetic operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("\nAddition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

# 12. Dot Product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot = np.dot(arr1, arr2)

print("\nDot Product =", dot)

[1 4 3 2 6 7]
[[1 4]
 [3 2]
 [6 7]]
shape: (3, 2)
dimensin 2
int64
item size 8
[[9 9 9]
 [9 9 9]
 [9 9 9]]
linspace arr: [ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]
[2 4 6 7]
[7 6 4 2]
[[[ 3  4  1]
  [ 5  8  6]
  [ 2 11  4]
  [ 2  3  9]]

 [[ 2  4  8]
  [12  3  5]
  [ 6  1  7]
  [ 2  3  8]]

 [[12 34  5]
  [ 6  9  8]
  [23  4  7]
  [ 4  3 13]]

 [[34  2  1]
  [ 1  3  8]
  [56  9  0]
  [ 5  8  3]]]
8

4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows & Even Columns:
[[ 5  7]
 [13 15]]

Slice from second set:
[[ 2  4]
 [12  3]]

Odd replaced with -1:
 [[-1 56 78 -1]
 [-1 82 -1 24]]

Non-zero indices:
(array([0, 2, 4, 6]),)

Addition: [5 7 9]
Multiplication: [ 4 10 18]

Dot Product = 1875
