In [2]:
import numpy as np
a=np.array([6,7,5])
b=np.array([[5,6,9],[7,9,3]])
re=np.vstack((a,b))
print(re)


[[6 7 5]
 [5 6 9]
 [7 9 3]]


In [3]:
#2)flatten
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)
v=a.flatten()
print(v)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [9]:
#3) Reverse a NumPy Array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a[::-1, ::-1])

[[6 5 4]
 [3 2 1]]


In [20]:
import numpy as np
#4) Practice Operations
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.shape(a))
print("row:",a.shape[0])
print("column:",a.shape[1])
print(a)
#select each element
for i in a:
    for j in i:
        print(j,end=" ")
#select specific element
print("\n" , a[1][1])
print("\n" , a[1,1])
sum=0
for i in a:
    for j in i:
      sum=sum+j
print("sum:",sum)  
arr=np.array([2,5,8])
b=np.array([3,8,5])
print('addition:',arr+b) 
print('subtraction:',arr-b)
print('multiplication:',arr*b)
print('divition:',arr/b) 
b=np.array([[3,8,5],[3,2,1]])
print(a+b,a-b,a*b,a/b)
    
    
        






6
1
21
(2, 3)
row: 2
column: 3
[[1 2 3]
 [4 5 6]]
1 2 3 4 5 6 
 5

 5
sum: 21
addition: [ 5 13 13]
subtraction: [-1 -3  3]
multiplication: [ 6 40 40]
divition: [0.66666667 0.625      1.6       ]
[[ 4 10  8]
 [ 7  7  7]] [[-2 -6 -2]
 [ 1  3  5]] [[ 3 16 15]
 [12 10  6]] [[0.33333333 0.25       0.6       ]
 [1.33333333 2.5        6.        ]]


In [26]:
#5) Iterate 3D Array Using For Loop and nditer
a=np.array([
    [[1,4,3,2],[2,54,2,6]],
    [[2,4,8,9],[3,45,6,3]]
            ])
print(a)
for i in a:
    for j in i:
        for k in j:
            print(k,end=" ")
for k in np.nditer(a):
    print(k)            


[[[ 1  4  3  2]
  [ 2 54  2  6]]

 [[ 2  4  8  9]
  [ 3 45  6  3]]]
1 4 3 2 2 54 2 6 2 4 8 9 3 45 6 3 1
4
3
2
2
54
2
6
2
4
8
9
3
45
6
3


In [45]:
#6) Study the following program
from scipy import stats
arr1 = np.array([3, 3,3])
arr2 = np.array([1, 1,1])
avg=(arr1+arr2)/2
print("Average of array",avg)
combine=np.concatenate((arr1.flatten(),arr2.flatten()))
print(combine)
print("mean=",np.mean(combine))
print("median=",np.median(combine))
print("mode= " ,stats.mode(combine,keepdims=True).mode[0])


Average of array [2. 2. 2.]
[3 3 3 1 1 1]
mean= 2.0
median= 2.0
mode=  1
